//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvilProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.ModelConfiguration.Conventions;
    
    public partial class EP_DB : DbContext
    {
        public EP_DB()
            : base("name=EP_DB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
            modelBuilder.Entity<PageNews>();
            modelBuilder.Entity<TODO>();
            //throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PageNews> PageNews { get; set; }
        public DbSet<TODO> TODO { get; set; }
    }
}
