//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvilProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TODO
    {
        public int Id { get; set; }
        public string project_name { get; set; }
        public string description { get; set; }
        public System.DateTime add_date { get; set; }
        public Nullable<System.DateTime> done_date { get; set; }
    }
}
